=== neg99/TimeTable/data/_annot/annot.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns="" xmlns:an="http://statmod.ru/annotations" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://statmod.ru/annotations" id="annotations">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="annotations">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="an:notes"/>
				<xs:element ref="an:cycle"/>
			</xs:choice>
			<xs:attribute name="spec" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="cycle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="an:name" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="an:annot" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="style" type="an:styleType" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="notes" type="an:stringWithLang"/>
	<xs:element name="name" type="an:stringWithLang"/>
	<xs:element name="annot">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="an:header"/>
				<xs:element ref="an:spec" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="header">
		<xs:complexType mixed="false">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="an:course"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="course">
		<xs:complexType>
			<xs:attribute name="id" type="an:courseId" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="stringWithLang" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="an:spec"/>
		</xs:sequence>
		<xs:attribute ref="xml:lang"/>
	</xs:complexType>
	<xs:element name="spec">
		<xs:complexType>
			<xs:attribute name="code" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="courseId">
		<xs:restriction base="xs:string">
			<xs:pattern value="/[a-z]+[_[a-z]]+/"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="styleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="no_duration"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== neg99/TimeTable/data/_annot/mm_an.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<annotations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://statmod.ru/annotations" xsi:schemaLocation="http://statmod.ru/annotations annot.xsd" spec="mm">
	<notes>
Структура образования на специализации Математическое Моделирование (кафедра статистического моделирования, отделение Прикладной математики и информатики мат-меха).	
	
Студенты обучаются на специализации в течение 3-х лет, с 3-го по 5-й курсы. В осеннем семестре 5-го курса занятия на факультете занимают 2-3 дня в неделю. В весенний семестр 5-го курса &ndash; 1 день в неделю. На 3-м и 4-м курсах занятия очень плотные, свободных дней практически нет.
	</notes>
	<cycle>
		<name>Вероятностный цикл</name>
		<annot>
			<header>
				<course id="all_teorver_pract"/>
				<course id="all_teorver_kurs"/>
			</header>
Годовой курс &laquo;Теория вероятностей&raquo; (3 курс, 5 и 6 семестры) для всего отделения читается кафедрой Теории Вероятностей и Математической Статистики. Общекафедральные практические занятия в нашей группе ведет наша же кафедра (в отличие от других кафедр отделения), что обеспечивает достаточно пристойное освоение студентами понятийных и технических аспектов этой науки. Курс теории вероятностей поддерживается, кроме того, курсовой работой по этому предмету. 
		</annot>
		<annot>
			<header>
				<course id="mm_statmod"/>
			</header>
 Курс включает в себя моделирование случайных величин, методы Монте-Карло. Частично поддерживается спец. выч. практикумом в 6 семестре.
		</annot>
		<annot>
			<header>
				<course id="all_statmod"/>
			</header>
В целом программа этой половины курса аналогична программе специального курса &laquo;Методы статистического моделирования&raquo;. Разница состоит в том, что в этом курсе изложение в меньшей степени использует продвинутые вероятностные понятия (так как студенты остальных  кафедр хуже наших ориентируются в вероятности). Поэтому и нашим студентам этот курс оказывается полезным (особенно не очень сильным). Курс поддерживается практическими занятиями. 
		</annot>
		<annot>
			<header>
				<course id="all_finmodel"/>
			</header>
 Программа курса включает в себя теорию арбитража в стохастических финансовых моделях, а также теорию расчетов для них.
		</annot>
		<annot>
			<header>
				<course id="all_finance_insurance"/>
			</header>
Курс посвящен моделям и процессам актуарной (страховой) математики.
		</annot>
	</cycle>
	<cycle>
		<name>Цикл &laquo;Дискретные системы&raquo;</name>
		<annot>
			<header>
				<course id="mm_automaton_base"/>
			</header>
Курс посвящен одной из главных тем специализации. В нем рассматриваются детерминированные автоматы, языки и связь между ними. На самом деле, этот курс дает начальные теоретические знания о построении компиляторов.
		</annot>
		<annot>
			<header>
				<course id="mm_fuzzy_sets"/>
			</header>
Курс посвящен развивающейся в данный момент области математики, известной как &laquo;нечеткая логика&raquo; (fuzzy logic). В курсе также рассматриваются различные методы принятия решений.
		</annot>
		<annot>
			<header>
				<course id="mm_automaton_struct"/>
			</header>
Спецкурс продолжает курс &laquo;Основы теории автоматных моделей&raquo;, упор делается на алгебру логики, на различные способы задания и построения логических функций и на их анализ.
		</annot>
		<annot>
			<header>
				<course id="mm_reliab_automaton"/>
			</header>
Спецкурс в некотором роде также продолжает &laquo;Основы теории автоматных моделей&raquo;, на этом курсе рассматриваются практические вопросы надежной (безотказной) работы автоматных моделей.
		</annot>
		<annot>
			<header>
				<course id="mm_petri_nets"/>
			</header>
Спецкурс дает обширные знания о сетях Петри, а также о дискретных процессах различных видов. Сети Петри будут особенно полезны тем, кто интересуется многопоточным программированием, так как они позволяют построить наглядную модель механизма семафоров для любого случая использования потоков.
		</annot>
		<annot>
			<header>
				<course id="mm_fuzzy_models"/>
			</header>
Курс является продолжением спецкурса &laquo;Теория нечетких множеств и ее приложения&raquo; и в нем рассматриваются задачи нечеткого моделирования в различных областях. 
		</annot>
		<annot>
			<header>
				<course id="mm_collective_behavior"/>
			</header>
На спецсеминаре обсуждаются вопросы оптимизации вероятностных нестационарных автоматов во взаимодействии со внешней средой и в игровых ситуациях. Также ведется подготовка к защите дипломных работ. 
		</annot>
	</cycle>
	<cycle>
		<name>Статистический цикл</name>
		<annot>
			<header>
				<course id="mm_appl_stat"/>
			</header>
Годовой курс математической статистики на специализации. Теоретическая часть включает в себя определения и основные результаты без доказательств для дисперсионного, регрессионного, факторного и дискриминантного анализа, а также анализа временных рядов. Половина занятий проводится за компьютером с целью овладения студентами пакетом STATISTICA.
		</annot>
		<annot>
			<header>
				<course id="mm_exper_design"/>
			</header>
Рассматриваются  регрессионные модели, исследуются D-, E- оптимальные планы.
		</annot>
		<annot>
			<header>
				<course id="all_stat"/>
			</header>
Формально &ndash; это снова курс математической статистики, читаемый всему отделению. Но это повторение оправдано, так как помогает освоить хоть и первичные, но сосем не простые понятия. К тому же, нет двух специалистов, которые читали бы курс статистики одинаково. 
		</annot>
		<annot>
			<header>
				<course id="mm_exper_design2"/>
			</header>
Спецсеминар продолжает &laquo;Анализ регрессионных моделей&raquo;.		
        </annot>
	</cycle>
	<cycle style="no_duration">
		<name>Цикл Программирование прикладных задач</name>
		<annot>
			<header>
				<course id="mm_prog_c_lang"/>
				<course id="mm_prog_c_pract"/>
			</header>
 Начало базового курса по программированию на C++. 
		</annot>
		<annot>
			<header>
				<course id="mm_prog_cpp"/>
			</header>
Продолжение курса по программированию на C++. 
		</annot>
		<annot>
			<header>
				<course id="mm_prog_cpp_advanced"/>
				<course id="mm_prog_cpp_pract"/>
			</header>
Происходит дальнейшее изучение C++. Курс включает в себя написание клиент серверного приложения, моделирующего систему массового обслуживания. Клиентская часть программы реализована на языке С#, серверная часть на С++.  Данные от сервера к клиентскому приложению передаются с помощью Socket. Моделирование на сервере осуществляется в помощью симуляционных потоков и использует элементы передачи управления. Их использование позволяет приблизить моделирование к реальным процессам, происходящим в система массового обслуживания. Особое внимание уделяется таким возможностям языка C#, как интеграции с другими приложениями (MS Graph, Excel). Так как материал сложный, то можно сказать, что результатом является знакомство студентов с описанными выше понятиями и выполнение задания &laquo;по образцу&raquo;.
		</annot>
		<annot>
			<header>
				<course id="mm_automaton_pract"/>
			</header>
Курс включает только самостоятельную работу студентов. Каждому студенту индивидуально дается задание в поддержку курса по автоматным моделям.
		</annot>
	<annot>
			<header>
				<course id="all_communication"/>
			</header>
В курсе собраны технологии оформления и презентации научных исследований. 
		</annot>
		<annot>
			<header>
				<course id="all_prog_matlab"/>
			</header>
Курс посвящен обучению студентов программированию статистических задач на языке R, специально предназначенном для этого.
 Задания, на основе которых происходит обучение, используют новый современный вероятностный и статистический материал, не включенный в другие курсы. 
		</annot>
	</cycle>
	<cycle>
		<name>Другое</name>
		<annot>
			<header>
				<course id="mm_parallel_comp"/>
			</header>
Курс посвящен изучению методов решения различных задач при помощи параллельных алгоритмов. В качестве примера используются задачи математической физики. Также в курсе рассматривается устойчивость некоторых алгоритмов, опирающихся на метод Монте-Карло. 
		</annot>
		<annot>
			<header>
				<course id="mm_idemp_algebra"/>
			</header>
Курс посвящен методам моделирования в идемпотентной алгебре, исследованию идемпотентной алгебры с операциями особого вида, а так же решению линейных уравнений в идемпотентной алгебре.
		</annot>
	</cycle>
</annotations>

=== neg99/TimeTable/data/_annot/sa_an.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<annotations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://statmod.ru/annotations" xsi:schemaLocation="http://statmod.ru/annotations annot.xsd" spec="sa">
	<notes>
Структура образования на специализации САПР (кафедра статистического моделирования, отделение Прикладной математики и информатики мат-меха).	
	
Студенты обучаются на специализации в течение 3-х лет, с 3-го по 5-й курсы. В осеннем семестре 5-го курса занятия на факультете занимают 2-3 дня в неделю. В весенний семестр 5-го курса &ndash; 1 день в неделю. На 3-м и 4-м курсах занятия очень плотные, свободных дней практически нет.
	</notes>
	<cycle>
		<name>Цикл &laquo;Теория вероятностей и случайные процессы&raquo;.</name>
		<annot>
			<header>
				<course id="all_teorver_pract"/>
				<course id="all_teorver_kurs"/>
			</header>
Годовой курс &laquo;Теория вероятностей&raquo; (3 курс, 5 и 6 семестры) для всего отделения читается кафедрой Теории Вероятностей и Математической Статистики. Общекафедральные практические занятия в нашей группе ведет наша же кафедра (в отличие от других кафедр отделения), что обеспечивает достаточно пристойное освоение студентами понятийных и технических аспектов этой науки. Курс теории вероятностей поддерживается, кроме того, курсовой работой по этому предмету. 
		</annot>
		<annot>
			<header>
				<course id="sa_statmod"/>
				<course id="sa_montecarlo"/>
			</header>
 Спецкурс состоит из трех частей: моделирование случайных величин, основы теории случайных процессов, методы Монте-Карло. В последней части рассматриваются задачи решения интегральных уравнений и систем линейных алгебраических уравнений. Поддерживается вышеобозначенным спецсеминаром и спец. выч. практикумом в
 восьмом семестре. 
		</annot>
		<annot>
			<header>
				<course id="all_statmod"/>
			</header>
В целом программа этой половины курса аналогична программе специального курса &laquo;Численное моделирование&raquo; и &laquo;Численные методы Монте-Карло&raquo;. Разница состоит в том, что в этом курсе изложение в меньшей степени использует продвинутые вероятностные понятия (так как студенты остальных  кафедр хуже наших ориентируются в вероятности). Поэтому и нашим студентам этот курс оказывается полезным (особенно не очень сильным). Курс поддерживается практическими занятиями. 
		</annot>
		<annot>
			<header>
				<course id="all_finmodel"/>
			</header>
 Программа курса включает в себя теорию арбитража в стохастических финансовых моделях, а также теорию расчетов для них.
		</annot>
		<annot>
			<header>
				<course id="all_finance_insurance"/>
			</header>
Курс посвящен моделям и процессам актуарной (страховой) математики.
		</annot>
		<annot>
			<header>
				<course id="sa_simul_stoch_proc"/>
			</header>
		</annot>
	</cycle>
	<cycle>
		<name>Цикл Моделирование систем и принятие решений</name>
		<annot>
			<header>
				<course id="sa_graph_theory"/>
			</header>
Курс целиком посвящен теории графов. Дополнительно идет ознакомление с TEX и дается домашнее задание по теории графов с обязательным выполнением в TEX.
		</annot>
		<annot>
			<header>
				<course id="sa_system_model"/>
				<course id="sa_system_model_pract"/>
			</header>
Годовой курс разделен на несколько частей. В первой половине  рассматриваются  как уже изученные методы моделирования случайных величин, так и общие понятия о системах. Вторая часть курса посвящена изучению различных подходов к исследованию моделей систем, среди которых: система , модель &laquo;хищник-жертва&raquo;, модель &laquo;поиска и слежения&raquo;.  Поддерживается практическими занятиями на спецсеминаре в 8 семестре. 
		</annot>
		<annot>
			<header>
				<course id="sa_decision_make"/>
			</header>
Курс посвящен методам решения многокритериальных задач (построение множества альтернатив, сужение множества альтернатив и выбор лучшей альтернативы).
		</annot>
		<annot>
			<header>
				<course id="sa_decision_make_pract"/>
			</header>
На семинаре рассматривается применение методов теории принятия решений на практике.
		</annot>
	</cycle>
	<cycle>
		<name>Статистический цикл</name>
		<annot>
			<header>
				<course id="sa_appl_stat"/>
			</header>
На спецсеминаре происходит знакомство студентов с математической статистикой и принципами прикладной статистики. Базой спецсеминара является теория вероятностей, на основе которой и излагаются понятия статистики. Занятия аудиторные и понимание проверяется на численных заданиях обработки небольших учебных данных, которые делаются либо вручную, либо частично с помощью Excel.
		</annot>
		<annot>
			<header>
				<course id="all_stat"/>
			</header>
Формально &ndash; это снова курс математической статистики, читаемый всему отделению. Но некоторое повторение оправдано, так как помогает освоить хоть и первичные, но совсем не простые понятия. К тому же, нет двух специалистов, которые читали бы курс статистики одинаково. 
		</annot>
		<annot>
			<header>
				<course id="sa_stat_pract"/>
			</header>
Преследует три цели. Первая - познакомить студентов со статистическими пакетами (в основном это пакет STATISTICA, менее мощный, чем другие пакеты, но обеспечивающий хорошую наглядность результатам отработок). Вторая цель &ndash; закрепить на материале одномерной статистики и регрессионного анализа понимание основных понятий статистики при обработке реальных (хоть и учебных) массивов. Наконец, ставится цель показать, что бездумное (автоматическое) применение статистических процедур может привести к ложным выводам. Можно сказать, что прививается культура статистической обработки данных.
        </annot>
	</cycle>
	<cycle style="no_duration">
		<name>Цикл Программирование прикладных задач</name>
		<annot>
			<header>
				<course id="sa_prog_c_lang"/>
				<course id="sa_prog_c_pract"/>
			</header>
 Начало базового курса по программированию на С. На спецсеминаре  дается теория, на занятиях в дисплейном классе  &ndash; несколько учебных задач. Завершается курс написанием диалоговой программы для построения гистограммы распределения. 
		</annot>
		<annot>
			<header>
				<course id="sa_prog_cpp"/>
			</header>
В качестве теории продолжается обучение основам С и начинается обучение объектно-ориентированному программированию на C++ (полсеместра). На занятиях в дисплейном классе идет освоение Visual C++, MFC. Задание для компьютерной реализации включает в себя создание одной большой программы с интерфейсом под Windows, реализующей моделирование распределений. Делается попытка создания программы в виде небольшого проекта, в котором каждый участник отвечает за отдельную часть. Успешность такой попытки зависит от уровня студентов. Курс также включает в себя небольшое задание по моделированию, оформляемое в ТЕХ. 
		</annot>
		<annot>
			<header>
				<course id="sa_prog_cpp_advanced"/>
				<course id="sa_prog_threads"/>
			</header>
Происходит дальнейшее изучение C++. Курс включает в себя написание клиент серверного приложения, моделирующего систему массового обслуживания. Клиентская часть программы реализована на языке С#, серверная часть на С++.  Данные от сервера к клиентскому приложению передаются с помощью Socket. Моделирование на сервере осуществляется в помощью симуляционных потоков и использует элементы передачи управления. Их использование позволяет приблизить моделирование к реальным процессам, происходящим в система массового обслуживания. Особое внимание уделяется таким возможностям языка C#, как интеграции с другими приложениями (MS Graph, Excel). Так как материал сложный, то можно сказать, что результатом является знакомство студентов с описанными выше понятиями и выполнение задания &laquo;по образцу&raquo;.
		</annot>
		<annot>
			<header>
				<course id="sa_montecarlo_pract"/>
			</header>
Курс включает только самостоятельную работу студентов. Каждому студенту индивидуально дается три задачи по материалу курса &laquo;Численные методы Монте-Карло&raquo;. Среда реализации не оговаривается, но обычно студенты выбирают MATLAB или Visual C++.
		</annot>
		<annot>
			<header>
				<course id="all_communication"/>
			</header>
В курсе собраны технологии оформления и презентации научных исследований. 
		</annot>
	<annot>
			<header>
				<course id="all_prog_matlab"/>
			</header>
Курс посвящен обучению студентов программированию статистических задач на языке R, специально предназначенном для этого.
 Задания, на основе которых происходит обучение, используют новый современный вероятностный и статистический материал, не включенный в другие курсы. 
		</annot>
	</cycle>
	<cycle>
		<name>Другое</name>
		<annot>
			<header>
				<course id="sa_automaton_model"/>
			</header>
Рассматриваются различные вопросы, связанные с конечно-автоматными моделями: представимость языков, абстрактный анализ и синтез, оптимизация, 
		</annot>
		<annot>
			<header>
				<course id="sa_parallel_comp"/>
			</header>
Курс посвящен изучению методов решения различных задач при помощи параллельных алгоритмов. В качестве примера используются задачи математической физики. Также в курсе рассматривается устойчивость некоторых алгоритмов, опирающихся на метод Монте-Карло.
		</annot>
	</cycle>
</annotations>
