=== neg99/TimeTable/data/_courses/spec.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?><xs:schema xmlns="" xmlns:co="http://statmod.ru/courses" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://statmod.ru/courses" id="courses">	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>	<xs:element name="courses">		<xs:complexType>			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="co:course"/>			</xs:choice>			<xs:attribute name="spec" type="co:specType" use="required"/>			<xs:attribute name="year" type="xs:string" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="course">		<xs:complexType>			<xs:sequence>				<xs:element ref="co:name" minOccurs="0"/>				<xs:element ref="co:prof" minOccurs="0"/>				<xs:element ref="co:part" minOccurs="0" maxOccurs="unbounded"/>				<xs:element ref="co:questions" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="semester" type="co:semesterNo"/>			<xs:attribute name="year" type="co:yearNo"/>			<xs:attribute name="class" type="co:classType"/>			<xs:attribute name="extras" type="xs:string"/>			<xs:attribute name="hours" type="xs:unsignedByte"/>			<xs:attribute name="exam" type="co:examType"/>			<xs:attribute name="year_equiv" type="xs:string"/>			<xs:attribute name="alias" type="co:courseId"/>		</xs:complexType>	</xs:element>	<xs:element name="name" type="co:stringWithLang"/>	<xs:element name="prof">		<xs:complexType>			<xs:attribute name="id" type="co:profId"/>		</xs:complexType>	</xs:element>	<xs:element name="questions">		<xs:complexType>			<xs:sequence>				<xs:element ref="co:file_name"/>			</xs:sequence>			<xs:attribute name="file" type="xs:anyURI"/>		</xs:complexType>	</xs:element>	<xs:element name="part">		<xs:complexType>			<xs:all>				<xs:element ref="co:prof"/>			</xs:all>			<xs:attribute name="type" type="xs:string"/>			<xs:attribute name="hours" type="xs:unsignedByte"/>		</xs:complexType>	</xs:element>	<xs:element name="file_name" type="xs:string"/>	<xs:complexType name="stringWithLang">		<xs:simpleContent>			<xs:extension base="xs:string">				<xs:attribute ref="xml:lang"/>			</xs:extension>		</xs:simpleContent>	</xs:complexType>	<xs:simpleType name="courseId">		<xs:restriction base="xs:string">			<xs:pattern value="[a-z](_|[a-z0-9])+"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="profId">		<xs:restriction base="xs:string">			<xs:pattern value="[a-z]{2}_([a-z])+"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="semesterNo">		<xs:restriction base="xs:integer">			<xs:minInclusive value="5"/>			<xs:maxInclusive value="10"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="yearNo">		<xs:restriction base="xs:integer">			<xs:minInclusive value="3"/>			<xs:maxInclusive value="5"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="classType">		<xs:restriction base="xs:string">			<xs:enumeration value="с/к"/>			<xs:enumeration value="с/с"/>			<xs:enumeration value="общ."/>			<xs:enumeration value="ОПД"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="specType">		<xs:restriction base="xs:string">			<xs:enumeration value="sm"/>			<xs:enumeration value="sa"/>			<xs:enumeration value="mm"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="examType">		<xs:restriction base="xs:string">			<xs:enumeration value="зачет"/>			<xs:enumeration value="экз."/>			<xs:enumeration value="доп."/>			<xs:enumeration value=""/>		</xs:restriction>	</xs:simpleType></xs:schema>

=== neg99/TimeTable/mm_spec.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<?mso-infoPathSolution PIVersion="1.0.0.0" name="urn:courses:statmod-ru" language="ru" solutionVersion="1.0.0.27" productVersion="14.0.0" ?>
<?mso-application progid="InfoPath.Document"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://statmod.ru/courses" year="2012/2013" spec="mm" xsi:schemaLocation="http://statmod.ru/courses spec.xsd">
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="mm_prog_c_pract">
		<name xml:lang="ru">Выч. практика</name>
		<prof id="ay_shlemov"/>
	</course>
	<course semester="5" year="3" class="с/к" extras="СД1" hours="2" exam="экз." year_equiv="0.5" alias="mm_automaton_base">
		<name xml:lang="ru">Основы теории автоматных моделей</name>
		<prof id="en_mosyagina"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="3_5__mm_automaton_base.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="5" year="3" class="с/с" extras="СС1" hours="2" exam="зачет" year_equiv="0.5" alias="mm_prog_c_lang">
		<name xml:lang="ru">Теория и практика программирования</name>
		<prof id="ay_shlemov"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="2" exam="доп." year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" exam="доп." year_equiv="" alias="all_teorver_kurs">
		<name xml:lang="ru">Курсовая работа по теор. вер.</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="4" exam="зачет" year_equiv="1" alias="mm_prog_cpp">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="6" year="3" class="с/к" extras="СД2" hours="2" exam="" year_equiv="" alias="mm_fuzzy_sets">
		<name xml:lang="ru">Теория нечетких мн-в и ее приложения</name>
		<prof id="mk_chirkov"/>
	</course>
	<course semester="6" year="3" class="с/с" extras="СС2" hours="2" exam="зачет" year_equiv="0.5" alias="mm_statmod">
		<name xml:lang="ru">Методы статистич. моделирования</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="3" exam="экз." year_equiv="0.5" alias="all_stat">
		<name xml:lang="ru">Мат. модел. и обработка данных</name>
		<part type="lect" hours="2">
			<prof id="ms_ermakov"/>
		</part>
		<part type="pract" hours="1">
			<prof id="ai_korobeynikov"/>
		</part>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="mm_prog_cpp_advanced">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="7" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="mm_prog_cpp_pract">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="pv_shpilev"/>
	</course>
		<course semester="7" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_communication">
		<name xml:lang="ru">Современные средства и методы научной коммуникации в области статистического моделирования</name>
	<prof id="ai_korobeynikov"/>
	</course>
	<course semester="7" year="4" class="ОПД" extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finmodel">
		<name xml:lang="ru">Задачи фин. мат. и стат. мод-ия</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="СД2" hours="2" exam="экз." year_equiv="1" alias="mm_fuzzy_sets">
		<name xml:lang="ru">Теория нечетких мн-в и ее приложения</name>
		<prof id="mk_chirkov"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_67_mm_fuzzy_sets.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="7" year="4" class="с/к" extras="СД3" hours="2" exam="" year_equiv="" alias="mm_appl_stat">
		<name xml:lang="ru">Прикладная статистика</name>
		<prof id="np_alekseeva"/>
	</course>
	<course semester="7" year="4" class="с/с" extras="СС3" hours="2" exam="зачет" year_equiv="0.5" alias="mm_exper_design">
		<name xml:lang="ru">Анализ регрессионных моделей</name>
		<prof id="pv_shpilev"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_7__mm_exper_design.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="8" year="4" class="общ." extras="" hours="2" exam="экз." year_equiv="0.5" alias="all_statmod">
		<name xml:lang="ru">Мат. модел. и обработка данных</name>
		<prof id="sm_ermakov"/>
	</course>
	<course semester="8" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="mm_automaton_pract">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="mk_chirkov"/>
	</course>
	<course semester="8" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finance_insurance">
		<name xml:lang="ru">Элементы фин.математики</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="8" year="4" class="ОПД" extras="выб." hours="5" exam="экз." year_equiv="0.75" alias="all_prog_matlab">
		<name xml:lang="ru">Выч. методы и пакеты в стат.исследованиях</name>
		<part type="lect" hours="3">
			<prof id="ai_korobeynikov"/>
		</part>
		<part type="pract" hours="2">
			<prof id="ai_korobeynikov"/>
		</part>
	</course>
	<course semester="8" year="4" class="с/к" extras="СД3" hours="2" exam="экз." year_equiv="1" alias="mm_appl_stat">
		<name xml:lang="ru">Прикладная статистика</name>
		<prof id="np_alekseeva"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_78_mm_appl_stat.pdf">
			<co:file_name>2009/2010</co:file_name>
		</co:questions>
	</course>
	<course semester="8" year="4" class="с/к" extras="СД4 (1)" hours="2" exam="экз." year_equiv="0.5(1)" alias="mm_automaton_struct">
		<name xml:lang="ru">Вероятностные модели и параллелизм (Вероятностные автоматные модели)</name>
		<prof id="en_mosyagina"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_8__mm_automaton_struct.pdf">
			<co:file_name>2008/2009</co:file_name>
		</co:questions>
	</course>
	<course semester="8" year="4" class="с/к" extras="СД4 (2)" hours="2" exam="экз." year_equiv="0.5(1)" alias="mm_parallel_comp">
		<name xml:lang="ru">Вероятностные модели и параллелизм (Введение в парал. вычисления)</name>
		<prof id="sm_ermakov"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_8__mm_parallel_comp.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="8" year="4" class="с/с" extras="СС4" hours="2" exam="зачет" year_equiv="0.5" alias="mm_reliab_automaton">
		<name xml:lang="ru">Надежность автоматных моделей</name>
		<prof id="mk_chirkov"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="СД5" hours="4" exam="экз." year_equiv="1" alias="mm_petri_nets">
		<name xml:lang="ru">Сети Петри и моделирование систем</name>
		<prof id="mk_chirkov"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="5_9__mm_petri_nets.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="9" year="5" class="с/к" extras="СД6 (1)" hours="2" exam="экз." year_equiv="0.5(1)" alias="mm_idemp_algebra">
		<name xml:lang="ru">Нечеткие и алгебр.методы моделир-ия систем (Алгебр. методы моделирования систем)</name>
		<prof id="nk_krivulin"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="5_9__mm_idemp_algebra.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="9" year="5" class="с/к" extras="СД6 (2)" hours="2" exam="экз." year_equiv="0.5(1)" alias="mm_fuzzy_models">
		<name xml:lang="ru">Нечеткие и алгебр.методы моделир-ия систем (Нечеткие модели и системы)</name>
		<prof id="mk_chirkov"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="5_9__mm_fuzzy_models.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="9" year="5" class="с/с" extras="СС5" hours="2" exam="зачет" year_equiv="0.5" alias="mm_exper_design2">
		<name xml:lang="ru">Модельно-ориентированный анализ данных</name>
		<prof id="vb_melas"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="5_9__mm_exper_design2.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="10" year="5" class="с/с" extras="СС6" hours="2" exam="зачет" year_equiv="0.5" alias="mm_collective_behavior">
		<name xml:lang="ru">Модели коллективного поведения</name>
		<prof id="mk_chirkov"/>
	</course>
</courses>

=== neg99/TimeTable/data/_courses/sa_spec.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<?mso-infoPathSolution PIVersion="1.0.0.0" name="urn:courses:statmod-ru" language="ru" solutionVersion="1.0.0.27" productVersion="14.0.0" ?>
<?mso-application progid="InfoPath.Document"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://statmod.ru/courses" year="2012/2013" spec="sa" xsi:schemaLocation="http://statmod.ru/courses spec.xsd">
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_c_pract">
		<name xml:lang="ru">Выч. практика</name>
		<prof id="vb_christinich"/>
	</course>
	<course semester="5" year="3" class="с/к" extras="СД1" hours="2" exam="экз." year_equiv="0.5" alias="sa_graph_theory">
		<name xml:lang="ru">Структурное представление систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="5" year="3" class="с/с" extras="СС1" hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_c_lang">
		<name xml:lang="ru">Алгоритмические языки</name>
		<prof id="vb_christinich"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="2" exam="доп." year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" exam="доп." year_equiv="" alias="all_teorver_kurs">
		<name xml:lang="ru">Курсовая работа по теор. вер.</name>
		<prof id="vv_nekrutkin"/>
		<!--<co:questions xmlns:co="http://statmod.ru/courses" file="3_sm_sa_2009.pdf">
	<co:file_name>2008/2009</co:file_name>	</co:questions>
    	-->
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="4" exam="зачет" year_equiv="1" alias="sa_prog_cpp">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="vb_christinich"/>
	</course>
	<course semester="6" year="3" class="с/к" extras="СД2" hours="2" exam="" year_equiv="" alias="sa_montecarlo">
		<name xml:lang="ru">Численные методы Монте-Карло</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="6" year="3" class="с/с" extras="СС2" hours="2" exam="зачет" year_equiv="0.5" alias="sa_statmod">
		<name xml:lang="ru">Численное моделирование</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="3" exam="экз." year_equiv="0.5" alias="all_stat">
		<name xml:lang="ru">Мат. модел. и обработка данных</name>
		<part type="lect" hours="2">
			<prof id="ms_ermakov"/>
		</part>
		<part type="pract" hours="1">
			<prof id="ai_korobeynikov"/>
		</part>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_cpp_advanced">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_threads">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_communication">
		<name xml:lang="ru">Современные средства и методы научной коммуникации в области статистического моделирования</name>
	<prof id="ai_korobeynikov"/>
	</course>
<course semester="7" year="4" class="ОПД" extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finmodel">
		<name xml:lang="ru">Задачи фин. мат. и стат. мод-ия</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="СД2" hours="2" exam="экз." year_equiv="1" alias="sa_montecarlo">
		<name xml:lang="ru">Численные методы Монте-Карло</name>
		<prof id="tm_tovstik"/>
	<co:questions xmlns:co="http://statmod.ru/courses" file="4_7__sa_montecarlo.pdf">
									<co:file_name>2011/2012</co:file_name>
								</co:questions></course>
	<course semester="7" year="4" class="с/к" extras="СД3" hours="2" exam="" year_equiv="" alias="sa_system_model">
		<name xml:lang="ru">Моделирование систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="7" year="4" class="с/с" extras="СС3" hours="2" exam="зачет" year_equiv="0.5" alias="sa_appl_stat">
		<name xml:lang="ru">Численные методы статистики</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="8" year="4" class="общ." extras="" hours="2" exam="экз." year_equiv="0.5" alias="all_statmod">
		<name xml:lang="ru">Мат. модел. и обработка данных</name>
		<prof id="sm_ermakov"/>
	</course>
	<course semester="8" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="sa_montecarlo_pract">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="8" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finance_insurance">
		<name xml:lang="ru">Элементы фин. математики</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="8" year="4" class="ОПД" extras="выб." hours="5" exam="экз." year_equiv="0.75" alias="all_prog_matlab">
		<name xml:lang="ru">Выч. методы и пакеты в стат.исследованиях</name>
		<part type="lect" hours="3">
			<prof id="ai_korobeynikov"/>
		</part>
		<part type="pract" hours="2">
			<prof id="ai_korobeynikov"/>
		</part>
	</course>
	<course semester="8" year="4" class="с/к" extras="СД3" hours="2" exam="экз." year_equiv="1" alias="sa_system_model">
		<name xml:lang="ru">Моделирование систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="8" year="4" class="с/к" extras="СД4 (1)" hours="2" exam="экз." year_equiv="0.5(1)" alias="sa_stat_pract">
		<name xml:lang="ru">Анализ данных и стох. выч. методы (Анализ данных и стат. пакеты)</name>
		<prof id="ne_golyandina"/>
	<co:questions xmlns:co="http://statmod.ru/courses" file="4_8__sa_stat_pract.pdf">
									<co:file_name>2010/2011</co:file_name>
								</co:questions></course>
	<course semester="8" year="4" class="с/к" extras="СД4 (2)" hours="2" exam="экз." year_equiv="0.5(1)" alias="sa_parallel_comp">
		<name xml:lang="ru">Анализ данных и стох. выч. методы (Введение в парал. вычисления)</name>
		<prof id="sm_ermakov"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_8__sa_parallel_comp.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="8" year="4" class="с/с" extras="СС4" hours="2" exam="зачет" year_equiv="0.5" alias="sa_system_model_pract">
		<name xml:lang="ru">Моделирование систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="СД5" hours="4" exam="экз." year_equiv="1" alias="sa_automaton_model">
		<name xml:lang="ru">Автоматное моделирование</name>
		<prof id="en_mosyagina"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="5_99_sa_automaton_model.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="9" year="5" class="с/к" extras="СД6 (1)" hours="2" exam="экз." year_equiv="0.5(1)" alias="sa_simul_stoch_proc">
		<name xml:lang="ru">Моделирование случайных процессов и принятие решений (Моделирование случайных процессов)</name>
		<prof id="tm_tovstik"/>
	<co:questions xmlns:co="http://statmod.ru/courses" file="5_9__sa_simul_stoch_proc.pdf">
									<co:file_name>2011/2012</co:file_name>
								</co:questions></course>
	<course semester="9" year="5" class="с/к" extras="СД6 (2)" hours="2" exam="экз." year_equiv="0.5(1)" alias="sa_decision_make">
		<name xml:lang="ru">Моделирование случайных процессов и принятие решений (Принятие решений)</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="9" year="5" class="с/с" extras="СС5" hours="2" exam="зачет" year_equiv="0.5" alias="sa_simul_stoch_proc_pract">
		<name xml:lang="ru">Моделирование случайных процессов</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="10" year="5" class="с/с" extras="СС6" hours="2" exam="зачет" year_equiv="0.5" alias="sa_decision_make_pract">
		<name xml:lang="ru">Принятие решений</name>
		<prof id="ya_sushkov"/>
	</course>
</courses>

=== neg99/TimeTable/data/_courses/mm_spec.xml
<?xml version="1.0" encoding="utf-8"?>
<?mso-infoPathSolution PIVersion="1.0.0.0" name="urn:courses:statmod-ru" language="ru" solutionVersion="1.0.0.27" productVersion="14.0.0" ?>
<?mso-application progid="InfoPath.Document"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://statmod.ru/courses" year="2016/2017" spec="mm" xsi:schemaLocation="http://statmod.ru/courses spec.xsd">
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="ball_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bmm_prog_c_pract">
		<name xml:lang="ru">Спец.выч. практикум</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="ball_tex">
		<name xml:lang="ru">Выч. практикум</name>
		<prof id="ai_korobeynikov"/>
	</course>
	<course semester="5" year="3" class="спец." extras="" hours="2" exam="экз." year_equiv="0.5" alias="bsa_graph_theory">
		<name xml:lang="ru">Структурное представление систем</name>
		<prof id="ya_sushkov"/>
	</course>
 	<course semester="5" year="3" class="спец." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bmm_prog_c_lang">
		<name xml:lang="ru">Теория и практика программирования</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="2" exam="доп." year_equiv="0.5" alias="ball_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" exam="доп." year_equiv="" alias="ball_teorver_kurs">
		<name xml:lang="ru">Курсовая работа по теор. вер.</name>
		<prof id="pv_shpilev"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bmm_prog_cpp_pract">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="pv_shpilev"/>
	</course>
<course semester="6" year="3" class="спец." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bsa_prog_cpp_lang">
		<name xml:lang="ru">Программирование на С++</name>
		<prof id="pv_shpilev"/>
	</course>
		<course semester="6" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bmm_simul_pract">
		<name xml:lang="ru">Выч. практикум</name>
		<prof id="pv_shpilev"/>
	</course>
		<course semester="5" year="3" class="проф." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="ball_simul_discr">
		<name xml:lang="ru">Дискретное моделирование</name>
		<prof id="vv_nekrutkin"/>
	</course>
	<course semester="6" year="3" class="проф." extras="" hours="2" exam="зкз." year_equiv="0.5" alias="ball_simul">
		<name xml:lang="ru">Моделирование распределений</name>
		<prof id="vv_nekrutkin"/>
	</course>
	
	<course semester="7" year="4" class="общ." extras="" hours="3" exam="экз." year_equiv="0.5" alias="ball_stat">
		<name xml:lang="ru">Мат. модел. и обработка данных</name>
		<part type="lect" hours="2">
			<prof id="ms_ermakov"/>
		</part>
		<part type="pract" hours="1">
			<prof id="ai_korobeynikov"/>
		</part>
	</course>
	<course semester="7" year="4" class="спец." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bsa_prog_cpp_advanced">
		<name xml:lang="ru">Программирование и дискретные системы</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="bsa_prog_threads">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="yn_kashtanov"/>
	</course>
		<course semester="7" year="4" class="проф." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="ball_communication">
		<name xml:lang="ru">Современные средства и методы научной коммуникации в области статистического моделирования</name>
	<prof id="ai_korobeynikov"/>
	</course>
<course semester="7" year="4" class="спец." extras="" hours="4" exam="экз." year_equiv="1" alias="bmm_fuzzy_sets">
		<name xml:lang="ru">Теория нечетких мн-в и ее приложения</name>
		<prof id="ay_ponomareva"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_67_mm_fuzzy_sets.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	<course semester="7" year="4" class="спец." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bmm_appl_stat">
		<name xml:lang="ru">Стохастический анализ данных</name>
		<prof id="np_alekseeva"/>
	</course>
		<course semester="7" year="4" class="проф." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="ball_exper_design">
		<name xml:lang="ru">Модельно-ориентированный анализ данных</name>
		<prof id="vb_melas"/>
  </course>
 <course semester="7" year="4" class="проф." extras="" hours="2" exam="экз." year_equiv="0.5" alias="ball_parallel_comp">
		<name xml:lang="ru">Метод Монте-Карло и параллельные вычисления</name>
		<prof id="sm_ermakov"/>
  </course>
	<course semester="8" year="4" class="проф." extras="" hours="4" exam="зачет" year_equiv="1" alias="bmm_idemp_algebra">
		<name xml:lang="ru">Алгебраические методы моделирования систем</name>
		<prof id="nk_krivulin"/>
	</course>
<course semester="8" year="4" class="проф." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bsa_prediploma">
		<name xml:lang="ru">Подготовка и оформление научных исследований</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="8" year="4" class="проф." extras="" hours="4" exam="экз." year_equiv="1" alias="ball_statprogR">
		<name xml:lang="ru">Выч. методы и пакеты в стат.исследованиях</name>
		<part type="lect" hours="2">
			<prof id="ai_korobeynikov"/>
		</part>
		<part type="pract" hours="2">
			<prof id="ai_korobeynikov"/>
		</part>
	</course>
	<course semester="8" year="4" class="проф." extras="" hours="4" exam="зачет" year_equiv="1" alias="bmm_stat_pract">
		<name xml:lang="ru">Анализ данных на компьютере</name>
		<prof id="np_alekseeva"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_78_mm_appl_stat.pdf">
			<co:file_name>2009/2010</co:file_name>
		</co:questions>
	</course>
	<course semester="8" year="4" class="спец." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="bmm_automaton_struct">
		<name xml:lang="ru">Вероятностные автоматные модели</name>
		<prof id="ay_ponomareva"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="4_8__mm_automaton_struct.pdf">
			<co:file_name>2008/2009</co:file_name>
		</co:questions>
	</course>
<course semester="8" year="4" class="спец." extras="" hours="4" exam="экз." year_equiv="1" alias="bmm_petri_nets">
		<name xml:lang="ru">Сети Петри</name>
		<prof id="ay_ponomareva"/>
		<co:questions xmlns:co="http://statmod.ru/courses" file="5_9__mm_petri_nets.pdf">
			<co:file_name>2011/2012</co:file_name>
		</co:questions>
	</course>
	
	<!--
	<course semester="9" year="5" class="с/к" extras="" hours="2" exam="экз." year_equiv="0.5" alias="all_mva">
		<name xml:lang="ru">Многомерный анализ данных</name>
		<prof id="ne_golyandina"/>
</course>
<course semester="9" year="5" class="с/к" extras="" hours="2" exam="экз." year_equiv="0.5" alias="all_adv_design">
		<name xml:lang="ru">Дополнительные главы теории оптимального планирования эксперимента</name>
		<prof id="vb_melas"/>
</course>
<course semester="9" year="5" class="с/c" extras="" hours="2" exam="зач." year_equiv="0.5" alias="mm_real_stat">
		<name xml:lang="ru">Применение статистических методов к реальным данным</name>
		<prof id="np_alekseeva"/>
</course>
	
	<course semester="10" year="5" class="с/к" extras="" hours="2" exam="экз." year_equiv="0.5" alias="mm_adv_stat">
		<name xml:lang="ru">Дополнительные главы математической статистики</name>
		<prof id="ms_ermakov"/>
	</course>
 <course semester="10" year="5" class="с/к" extras="" hours="2" exam="экз." year_equiv="0.5" alias="mm_stoch_comp">
		<name xml:lang="ru">Стохастические вычислительные методы</name>
		<prof id="sm_ermakov"/>
</course>
<course semester="10" year="5" class="с/c" extras="" hours="2" exam="зач." year_equiv="0.5" alias="mm_random_fields">
		<name xml:lang="ru">  Случайные поля и динамические методы Монте-Карло</name>
		<prof id="tm_tovstik"/>
	</course>
<course semester="10" year="5" class="с/c" extras="" hours="2" exam="зач." year_equiv="0.5" alias="mm_parallel_comp">
		<name xml:lang="ru">Параллельное программирование вероятностных задач</name>
		<prof id="yn_kashtanov"/>
</course>
-->
</courses>
