=== neg99/TimeTable/data/_staff/about.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
        <xs:element name="about">
                <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element ref="br"/>
                                <xs:element ref="p"/>
                                <xs:element ref="ol"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="br" type="xs:string"/>
        <xs:element name="i">
                <xs:complexType mixed="true">
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element ref="spec"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="b">
                <xs:complexType mixed="true">
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element ref="spec"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="spec">
                <xs:complexType>
                        <xs:attribute name="code" type="xs:string" use="required"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="a">
                <xs:complexType mixed="true">
                        <xs:attribute name="href" type="xs:string" use="required"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="ol">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="li" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="li" type="xs:string"/>

        <xs:element name="p">
                <xs:complexType mixed="true">
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element ref="i"/>
                                <xs:element ref="span"/>
                                <xs:element ref="spec"/>
                                <xs:element ref="b"/>
                                <xs:element ref="a"/>
                                <xs:element name="br"/>
                        </xs:choice>
                </xs:complexType>
        </xs:element>
        <xs:element name="span">
                <xs:complexType mixed="true">
                        <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
        </xs:element>
</xs:schema>

=== neg99/TimeTable/data/_staff/about_ag_bart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<about xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="about.xsd">
        <!-- Текст -->
        <p>
                <i>5 марта 2007 года Александр Георгиевич Барт скоропостижно скончался. Похоронен на Волковском лютеранском кладбище. Светлая ему память!</i><br/>
                <a href="/vega/bart/bart_in_memory.htm">Памяти А.Г. Барта</a><br/>
                <a href="/vega/bart/ag_bart.htm">Александр Георгиевич Барт — человек светлой души</a><br/><br/>
                <a href="/vega/bart/vvv01.htm">Сорок лет общения с Александром Георгиевичем Бартом</a>
        </p>
        <br/>
        <p>Барт А.Г. основал на кафедре биометрическое направление работ
на базе широко известного городского Биометрического Семинара. Главной
целью этих исследований является разработка математического
аппарата, отражающего логику развития биосистем. Методы работы
опираются
на непосредственные контакты с экспериментаторами по решению реальных
проблем медико-биологического плана. </p>
        <p>Имеются реальные применения результатов, в частности, в
вопросах паразитологии, нейрофизиологии, иммунологии (бронхиальная
астма, гингивит), в кардиологии, в анализе раневых процессов, в вопросах
влияния рекламы на маркетинг продаж и т.д. </p>
        <p>По его руководством велись совместные работы с НИИ эволюционной физиологии и биохимии им.
И.М.Сеченова и с ВМА, в которых участвовали
также студенты и аспиранты кафедры.</p>
</about>

=== neg99/TimeTable/data/_staff/about_vn_solntsev.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<about xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="about.xsd">
			<!-- Текст -->
			<p>
				<b>I. Методы стохастической оптимизации &ndash; случайного поиска
экстремума.</b>
			</p>
			<p>Исследования в области методов стохастической оптимизации
(случайный поиск) ориентируются преимущественно на задачи идентификации
моделей (оценивание параметров в сложных нелинейных моделях или поиск
экстремумов для негладких многоэкстремальных функций переменной
размерности).</p>
			<p>
				<b>II. Развитие методов прикладной многомерной статистики.</b>
			</p>
			<p>Исследования в математической статистике направлены на
установление связей между различными методами многомерной статистики,
развитие единого подхода С.Р. Рао к системе методов многомерной
статистики, не опирающегося на невырожденное многомерное нормальное
распределение и выработку методологии их применения в задачах анализа
данных.</p>
			<p>
				<b>III. Развитие методов анализа и прогноза временных рядов
("гусеница").</b>
			</p>
			<p>Исследования в теории анализа процессов были ориентированы на
исследование свойств и разработку возможных направлений развития метода
"Гусеница", а также вейвлет-анализа.</p>
			<p>
				<b>IV. Статистический анализ данных в технике, химии,
гидрологии,
медицине, экономике.</b>
			</p>
			<p>
				<b>Преподавание.</b>
			</p>
			<p>В 1974-94 гг. вел практические занятия по теории вероятностей,
читал спецкурсы по математической статистике и дополнительным главам
математической статистики на Курсах повышения математической
квалификации инженеров при ЛГУ. </p>
			<p> С 2005 г. &ndash; чтение курса "Биостатистика на ЭВМ" в
межфакультетской магистерской программе "Общественное здоровье".</p>
		</about>

=== neg99/TimeTable/data/_staff/about_vv_nekrutkin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<about xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="about.xsd">
			<br/>
			<p>
				<i>Из ответа на вопрос студентов 5-го курса &laquo;Что бы Вы пожелали студентам&raquo;:</i>
			</p>
			<p>&laquo;Есть некоторое, я даже не знаю, правило&nbsp;–&nbsp;не правило:</p>
			<ol>
				<li>надо стремиться делать только то, что тебе нравится</li>
				<li>все, что ты делаешь, надо стараться делать хорошо, вне зависимости от того, нравится тебе или не нравится.</li>
			</ol>
			<p>А по совокупности эти вещи означают вот что: не всегда возможно делать то, что тебе нравится (хоть и надо стремиться). И <span class="interesting">если ты попадаешь в ситуацию, которая тебе не нравится, то ее надо отработать и с очень большой вероятностью она тебе начнет нравиться</span>.
</p>
			<p>Это - общее правило, и для меня тоже. И к вам оно сильно, вообще говоря, относится, потому что, так или иначе, но вы попали в ту ситуацию, в которую попали: ошиблись вы или не ошиблись (&laquo;не тот самолет&raquo;, &laquo;не тот город&raquo;, &laquo;не в ту дверь зашел&raquo;), по каким причинам &ndash; это неважно. 
</p>
			<p>Это мое мнение и является объяснением моего отношения к вам.&raquo;</p>
		</about>
